Remove bitarray for snellius
Bitarray does not build on the new Snellius cluster:

(env_GenNet_2020) [ahilten@int3 GenNet]$ pip install bitarray
Collecting bitarray
  Using cached bitarray-2.3.4.tar.gz (88 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: bitarray
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /gpfs/home2/ahilten/env_GenNet_2020/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/setup.py'"'"'; __file__='"'"'/gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /gpfs/scratch1/nodespecific/int3/ahilten/pip-wheel-qzkdg1ar
       cwd: /gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/util.py -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/__init__.py -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/test_util.py -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/pythoncapi_compat.h -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/bitarray.h -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/test_data.pickle -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/py.typed -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/util.pyi -> build/lib.linux-x86_64-3.6/bitarray
  copying bitarray/__init__.pyi -> build/lib.linux-x86_64-3.6/bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/bitarray
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/gpfs/home2/ahilten/env_GenNet_2020/include -I/usr/include/python3.6m -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.6/bitarray/_bitarray.o
  bitarray/_bitarray.c:12:10: fatal error: Python.h: No such file or directory
     12 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
Failed to build bitarray
Installing collected packages: bitarray
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: /gpfs/home2/ahilten/env_GenNet_2020/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/setup.py'"'"'; __file__='"'"'/gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /gpfs/scratch1/nodespecific/int3/ahilten/pip-record-wxepv9oz/install-record.txt --single-version-externally-managed --compile --install-headers /gpfs/home2/ahilten/env_GenNet_2020/include/site/python3.6/bitarray
         cwd: /gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/
    Complete output (28 lines):
    running install
    /gpfs/home2/ahilten/env_GenNet_2020/lib64/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/util.py -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/__init__.py -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/test_util.py -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/pythoncapi_compat.h -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/bitarray.h -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/test_data.pickle -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/py.typed -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/util.pyi -> build/lib.linux-x86_64-3.6/bitarray
    copying bitarray/__init__.pyi -> build/lib.linux-x86_64-3.6/bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/bitarray
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/gpfs/home2/ahilten/env_GenNet_2020/include -I/usr/include/python3.6m -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.6/bitarray/_bitarray.o
    bitarray/_bitarray.c:12:10: fatal error: Python.h: No such file or directory
       12 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /gpfs/home2/ahilten/env_GenNet_2020/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/setup.py'"'"'; __file__='"'"'/gpfs/scratch1/nodespecific/int3/ahilten/pip-install-6ckv8v3g/bitarray_fadd1cd55408429fbe58c2bfa0ec6ab7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /gpfs/scratch1/nodespecific/int3/ahilten/pip-record-wxepv9oz/install-record.txt --single-version-externally-managed --compile --install-headers /gpfs/home2/ahilten/env_GenNet_2020/include/site/python3.6/bitarray Check the logs for full command output.